language: node_js
node_js:
  - 8
cache:
  directories:
    - node_modules
before_script:
  - npm install --prefix PedalPatrol
  - npm run setup --prefix PedalPatrol
script:
  - npm test --prefix PedalPatrol && npm run coverage --prefix PedalPatrol