language: node_js
node_js:
  - 8
cache:
  directories:
    - node_modules
before_script:
  - npm install --prefix PedalPatrol
script:
  - npm test --prefix PedalPatrol

jobs:
  include:
    - stage: Produce Coverage
      node_js: node
      script: 
        - npm run test:coverageTravis --prefix PedalPatrol
