import firebase from 'firebase';
import config from '../config/config.json';

/**
 * Class for the firebase database connection and operations
 */
class FirebaseDatabase {
	constructor() {
		if (!firebase.apps.length) {
			firebase.initializeApp(config.databaseConfig);
		}
		this.setupDatabaseRef();
	}

	/**
	 * Set up the database reference to the PProject table
	 */
	setupDatabaseRef() {
		this.ref = firebase.database().ref('PProject/');
	}

	/**
	 * Accesses Firebase data to sign in with email and password.
	 * This function is called asynchronously. Use 'async' and 'await'.
	 *
	 * @param {string} email - A user's email
	 * @param {string} password - A user's password
	 * @param {Function} onError - A function callback to execute on error
	 */
	signIn(email, password, onError) {
		firebase.auth().signInWithEmailAndPassword(email, password).catch(onError);
	}


	/** 
	 * Write to the database in table 'Bike' using the id as the child. Adds a date time and owner to the data
	 *
	 * @param {Object} bikeData - Bike data to add to the database
	 * @param {Function} onSuccess - A function callback to execute on the success of writing to the database
	 * @param {Function} onError - A function callback to execute on an error when writing to the database
	 */
	writeBikeData(bikeData, onSuccess, onError) {
		bikeData.datetime = this.getDateTime(); 
		bikeData.owner = this.getCurrentUser();
		// console.log(bikeData.datetime);
		this.ref.child('Bike/').child(bikeData.id).set(bikeData, onSuccess).catch(onError);
	}

	/**
	 * Overwrites data in the database by reading the data, merging it with the new values and writing back to the same ID.
	 *
	 * @param {Object} newBikeData - New data to write
	 * @param {Function} onSuccess - A function callback to run when writing is successful
	 * @param {Function} onErorr - A function callback to run when writing fails
	 */
	editBikeData(newBikeData, onSuccess, onError) {
		const bikeID = newBikeData.id;

		this.ref.child('Bike/').once('value', (snapshot) => {
			let bikeData = snapshot.val();
			let originalBikeData = bikeData[bikeID];
			let updatedObj = this.merge(originalBikeData, newBikeData);
			this.ref.child('Bike/').child(bikeID).set(updatedObj, onSuccess).catch(onError);
		}).catch((error) => {
			onError(error);
			console.log(error);
		});
	}

	/**
	 * Merges the data of two objects. Keeps everything in originalObj, adds any key in newObj and overwrites duplicates in originalObj.
	 *
	 * @param {Object} originalObj - Original data to replace
	 * @param {Object} newObj - New data to add
	 *
	 * @return {Object} Merged data
	 */
	merge(originalObj, newObj) {
		// key: the name of the object key
		// index: the ordinal position of the key within the object 
		Object.keys(newObj).forEach((key,index) => {
			originalObj[key] = newObj[key];
		});
		return originalObj; // Need to return original because it has datetime and owner
	}

	/**
	 * Read data from the bike table only once.
	 *
	 * @param {Function} callback - A function callback that is with the value(s) read
	 */
	readBikeDataOnce(callback) {
		this.ref.child('Bike/').once('value', callback);
	}

	/**
	 * Read data from the bike table every time there is a change in the database.
	 *
	 * @param {Function} callback - A function callback that is with the value(s) read
	 */
	readBikeDataOn(callback) {
		this.ref.child('Bike/').on('value', callback);
	}

	/**
	 * Returns a new unique key generated by the database.
	 *
	 * @return {string} A newly generated unique key
	 */
	getNewBikeID() {
		return this.ref.child('Bike').push().key;
	}

	/**
	 * Generates the current time and returns it in milliseconds.
	 * 
	 * @return {Number} Returns the current time in milliseconds
	 */
	getDateTime() {
		return (new Date()).getTime();
	}

	/**
	 * Makes the database go offline.
	 */
	goOffline() {
		firebase.database().goOffline();
	}

	/**
	 * Removes an item from the database by a supplied key.
	 *
	 * @param {string} key - An id in the database
	 */
	removeBikeItem(key) {
		this.ref.child('Bike').child(key).remove();
	}

	/**
	 * Returns the currently logged in user's id.
	 *
	 * @return {string} user id of the currently logged in user
	 */
	getCurrentUser() {
		if (firebase.auth().currentUser !== null) {
			console.log("user id: " + firebase.auth().currentUser.uid);
			return firebase.auth().currentUser.uid;
		} else {
			return null;
		}
	}
}

export default FirebaseDatabase;